on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Set up api key 
      run: echo "API_KY=123" >> $GITHUB_ENV

    - name: use API key
      run: exho "USing API KEy $API_KEY"

  
    # runs-on: ubuntu-latest 
    # steps:
    #   - run: |
    #       depracted=true
    #       if [[ depracted ]] ; then 
    #         echo "::warning::Depracted fucntion"
    #       fi
